### ISSUE TITLE
Why use vagrant for testing?

### ISSUE THREAD

**Issue by thepenguinthatwants** [kibatic/ansible-traefik#28]
Hi!

I am wondering why you used vagrant for testing but not docker? Is it because of travis? Vagrant up does show the outcome but its quite slow.

Trying to learn how to test own roles and changing the setup without always running things straight on server.

**Comment by eliecharra** [comment]
Hm it's been quiet a long time ago testing this role :smile: It seems that vagrant is not used in automated tests. The Vagrantfile is here for developpement purposes.

Actually this role could be more tested, have a look at #20 ;)

If you wanna learn how to deep test roles, please look at this another role we maintain which is deeply tested using docker / goss : https://github.com/kibatic/docker-systemd/tree/master/tests
