### ISSUE TITLE
Hardcoded .j2 extension in template

### ISSUE THREAD

**Issue by einnjo** [kibatic/ansible-traefik#37]
Thank you for the awesome role. Is there any specific reason why the template extension is hardcoded?
https://github.com/kibatic/ansible-traefik/blob/46389ec72e7460995fb1601b102dce69caa12403/tasks/main.yml#L5

Most ansible roles don't hardcode the extension and leave that decision to the end user.

**Comment by jcrombez** [comment]
There i snot specific reason, no.
If you want, you can create a PR and i'll merge it.
